# site properties and page defaults
title: RUC-NLPIR
subtitle: 
description: RUC-NLPIR lab is from Gaoling School of Artificial Intelligence, Renmin University of China. This lab is under the supervision of Prof. Zhicheng Dou, with special interests in information retrieval and natural language processing.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@RUC-NLPIR.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: RUC-NLPIR
  twitter: RUC-NLPIR
  youtube: RUC-NLPIR

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
