- id: arxiv:2401.06532
  title: 'INTERS: Unlocking the Power of Large Language Models in Search with Instruction Tuning'
  authors: 
  - Yutao Zhu
  - Peitian Zhang
  - Chenghao Zhang
  - Yifei Chen
  - Binyu Xie
  - Zhicheng Dou
  - Zheng Liu
  - Ji-Rong Wen
  publisher: arXiv
  type: paper
  date: '2024-1-12'
  link: https://arxiv.org/abs/2401.06532
