- id: arxiv:2401.06532
  title: 'INTERS: Unlocking the Power of Large Language Models in Search with Instruction Tuning'
  authors: 
  - Yutao Zhu
  - Peitian Zhang
  - Chenghao Zhang
  - Yifei Chen
  - Binyu Xie
  - Zhicheng Dou
  - Zheng Liu
  - Ji-Rong Wen
  publisher: arXiv
  type: paper
  date: '2024-1-12'
  link: https://arxiv.org/abs/2401.06532
- id: arxiv:2401.03462
  title: "Soaring from 4K to 400K: Extending LLM's Context with Activation Beacon"
  authors: 
  - Peitian Zhang
  - Zheng Liu
  - Shitao Xiao
  - Ninglu Shao
  - Qiwei Ye
  - Zhicheng Dou
  publisher: arXiv
  type: paper
  date: '2024-1-7'
  link: https://arxiv.org/abs/2401.03462
- id: arxiv:2402.11626
  title: 'Metacognitive Retrieval-Augmented Large Language Models'
  authors: 
  - Yujia Zhou
  - Zheng Liu
  - Jiajie Jin
  - Jian-Yun Nie
  - Zhicheng Dou
  publisher: WWW
  type: paper
  date: '2024-2-18'
  link: https://arxiv.org/abs/2402.11626
- id: arxiv:2402.10548
  title: 'Cognitive Personalized Search Integrating Large Language Models with an Efficient Memory Mechanism'
  authors: 
  - Yujia Zhou
  - Qiannan Zhu
  - Jiajie Jin
  - Zhicheng Dou
  publisher: The ACM Web Conference 2024
  type: paper
  date: '2024-2-16'
  link: https://arxiv.org/abs/2402.10548
- id: doi:10.1109/TKDE.2023.3291006
  title: 'Integrated Personalized and Diversified Search Based on Search Logs'
  authors: 
  - Jiongnan Liu
  - Zhicheng Dou
  - Jian-Yun Nie
  - Ji-Rong Wen
  publisher: IEEE TKDE
  type: paper
  date: '2024-2-1'
  link: http://playbigdata.ruc.edu.cn/dou/publication/2024_TKDE_Integrated_Personalized_and_Diversified_Search_Based_on_Search_Logs.pdf
- id: doi:10.1145/3631989
  title: 'Personalized and Diversified: Ranking Search Results in an Integrated Way'
  authors: 
  - Shuting Wang
  - Zhicheng Dou
  - Jiongnan Liu
  - Qiannan Zhu
  - Ji-Rong Wen
  publisher: ACM TOIS
  type: paper
  date: '2024-1-22'
  link: https://doi.org/10.1145/3631989
- id: doi:10.1145/3639817
  title: 'Intent-oriented Dynamic Interest Modeling for Personalized Web Search'
  authors: 
  - Yutong Bai
  - Yujia Zhou
  - Zhicheng Dou
  - Ji-Rong Wen
  publisher: ACM TOIS
  type: paper
  date: '2024-2-9'
  link: https://dl.acm.org/doi/abs/10.1145/3639817
- id: arxiv:2312.11036
  title: 'UniGen: A Unified Generative Framework for Retrieval and Question Answering with Large Language Models'
  authors: 
  - Xiaoxi Li
  - Yujia Zhou
  - Zhicheng Dou
  publisher: AAAI
  type: paper
  date: '2024-2-20'
  link: https://arxiv.org/abs/2312.11036
